name: Build and Push to s3

# Controls when the workflow will run
on:
  workflow_dispatch:
  # Triggers the workflow on push event but only for the branch specified with in []
  push:
    branches: [ aws_lambda_test ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - if: github.event_name == 'workflow_dispatch'
        name: Force push changes
        run: |
          # git config --global user.name "Your Name"
          # git config --global user.email "your.email@example.com"
          # git checkout main
          # git merge --no-ff ${{ github.ref }}
          # git push --force origin main
          echo "THIS is workFlow dispatch"

      - if: github.event_name == 'workflow_dispatch'  
        name: Create local changes
        run: |
          echo "Hello World!" >> ~/.env
          
      - if: github.event_name == 'workflow_dispatch'
        name: Commit files
        run: |
          git config --local user.email "tic.dev@comakeit.com"
          git config --local user.name "comakeit-tic"
          git commit -a -m "updated DNS name in env"

      - if: github.event_name == 'workflow_dispatch'
        name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ap-south-1

       # Treating warnings as errors because process.env.CI = true
       # set CI=false to treat warnings as warnings
      - name: Build React App
        run:  npm install && CI=false npm run build

      - name: Deploy app build to S3 bucket
        run:  aws s3 sync ./build/ s3://wda-ui --delete