name: Build and Push to s3

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      dNSName:
        description: 'alb dns name'
        required: true
        type: string
  # Triggers the workflow on push event but only for the branch specified with in []
  push:
    branches: [ aws_lambda_test ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - if: github.event_name == 'workflow_dispatch'
        name: Update DNS name 
        run: |
          echo "Updating DNS Name in .env.production..."

          sed -i '/REACT_APP_API_BASE_URL/d' .env.production && echo 'REACT_APP_API_BASE_URL = "https://${{ github.event.inputs.dNSName }}"' >> .env.production
          
          git config --local user.email "tic.dev@comakeit.com"
          git config --local user.name "comakeit-tic"
          git commit -a -m "updated DNS name in env"

          echo "Deleting protection to the main branch..."

          curl -L \
          -X DELETE \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{secrets.WORKFLOW_TOKEN}}"\
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/coMakeIT-TIC/wda-ui/branches/main/protection


      - if: github.event_name == 'workflow_dispatch'
        name: Push changes
        uses: ad-m/github-push-action@master
        with:
          force: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - if: github.event_name == 'workflow_dispatch'
        name: Add protection to main branch
        run : |
          curl -X PUT \                  
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{secrets.WORKFLOW_TOKEN}}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -H "Content-Type: application/json" \
          https://api.github.com/repos/coMakeIT-TIC/wda-ui/branches/main/protection \
          -d '{"enforce_admins": null, "required_status_checks": null,"required_pull_request_reviews": {"dismiss_stale_reviews": false,"require_code_owner_reviews": false,"required_approving_review_count": 1},"restrictions": null}'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ap-south-1

       # Treating warnings as errors because process.env.CI = true
       # set CI=false to treat warnings as warnings
      - name: Build React App
        run:  npm install && CI=false npm run build

      - name: Deploy app build to S3 bucket
        run:  aws s3 sync ./build/ s3://wda-ui --delete