name: Build and Push to s3

# Controls when the workflow will run
on:
  # Triggers the workflow on push event but only for the branch specified with in []
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Push to Deploy Branch
        uses: ad-m/github-push-action@master
        with:
          branch: deploy
          directory: .
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ap-south-1

       # Treating warnings as errors because process.env.CI = true
       # set CI=false to treat warnings as warnings
      - name: Build React App
        run:  npm install && CI=false npm run build

      - name: Deploy app build to S3 bucket
        run:  aws s3 sync ./build/ s3://wda-ui --delete